### ISSUE TITLE
due_can requires can_common

### ISSUE THREAD

**Issue by rmcolbert** [collin80/M2RET#7]
Readme needs to include a reference to the can_common library for people building M2RET from scratch.

**Comment by Damian-R-Smith** [comment]
can_common is a dependency of due_can, not M2RET directly and is already mentioned in the due_can README so surely there is no reason to include it in the M2RET README? 

(As a sidenote; If you feel this is really needed then why not add it yourself and make a pull request to have it included?)

**Comment by rmcolbert** [comment]
Yes, Collin's due_can added a dependency and it is listed in its readme (but not above the fold on the home page so you need to dig into the readme). Adding it to the M2RET readme makes sense since someone compiling it for the first time will see it ... and someone updating their source will review it but may not review the other libraries.

________________________________

**Comment by Damian-R-Smith** [comment]
I see what you mean, yeah maybe it can do no harm to include this in the M2RET readme

**Comment by collin80** [comment]
Sorry I didn't get to this until now. I've updated the readme to point mcp2515 to my version and have added the can_common dependency right in this readme so that people are aware you need it. Hopefully this helps every in the future. Thanks for all of your comments.
