### ISSUE TITLE
2017-11-11 Commit breaks compat w/ Macchina mcp2515 library

### ISSUE THREAD

**Issue by rmcolbert** [collin80/M2RET#8]
Read Me points to the Macchina repo for mcp2515 but code needs updates added to Collin's fork. Either the read me should point to Collin's fork or a pull request to the Macchina repo should be created.

**Comment by Damian-R-Smith** [comment]
Can you provide the commit id for which one you are talking about? (I see no commits for 11th November 2017 in the history). Can you elaborate on the issue more so myself or others can look at it, or if you understand the issue why not just create the pull request yourself?

**Comment by rmcolbert** [comment]
Commit #7e26a9f

I don't know why it broke, I rolled back commits until I found code that would compile.

________________________________

**Comment by Damian-R-Smith** [comment]
Thanks. I think my local is behind by a few commits so I didn't see a compile issue. I'll try to look into this and see what happened.
